---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: widget-api
  labels:
    app: widget-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: widget-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: widget-api
    spec:
      containers:
        - name: widget-api
          image: pawelkonior/fastapi:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017
            - name: REDIS_URI
              value: redis://redis:6379/0
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: widget-api-secrets
                  key: secret-key
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi



